function getYouTubeId(url: string) {
  const match = url.match(
    /(?:youtube\.com\/shorts\/|youtube\.com\/watch\?v=|youtu\.be\/)([^?&/]+)/
  );

  return match ? match[1] : "";
}

const works = [
  {
    title: "Goojodoq Turbo Fan",
    video: "https://youtube.com/shorts/WnA_9ZEnDPs",
  },
  {
    title: "Animasi AI Video",
    video: "https://youtube.com/shorts/uQFet6dEheE",
  },
  {
    title: "Motion Graphic AI Video",
    video: "https://youtube.com/shorts/eauf9yma_ZM",
  },
  {
    title: "UGC VIDEO Review Choco Pie",
    video: "https://youtube.com/shorts/oQ2nV2MWZkA",
  },
  {
    title: "Mireya Setting Spray",
    video: "https://youtube.com/shorts/LJjLCpnzUo4",
  },
  {
    title: "UGC Advertising Human Acc",
    video: "https://youtube.com/shorts/lAA3b7pVgf8",
  },
  {
    title: "UGC AI Video Project",
    video: "https://youtube.com/shorts/xRizRlJ7W6M",
  },
  {
    title: "Anime Kids Family Ai",
    video: "https://youtube.com/shorts/L_dRehEZGUE",
  },
  {
    title: "Timelapse AI Video",
    video: "https://youtube.com/shorts/AkKETdL9-74",
  },
  {
    title: "Transform Power Rangers AI Video",
    video: "https://youtube.com/shorts/0ooEUnePyas",
  },
];

const showcaseVideos = [
  {
    title: "Animasi Video Mama & Baby",
    video: "https://youtu.be/AeO-xdNvfb8",
  },
  {
    title: "AI Video Project Storytelling Church",
    video: "https://youtu.be/WQNZcf43mGg",
  },
  {
    title: "AI Video Project Anime Kids Family",
    video: "https://youtu.be/oBmXqNXiGO8",
  },
  {
    title: "UGC Advertising or Film Video by Full Ai",
    video: "https://youtu.be/ENGbirLyTMQ",
  },
];

export default function Home() {
  return (
    <main className="portfolio-page">
      <section className="portfolio-container">

        {/* HEADER */}
        <header className="portfolio-header">
          <div className="portfolio-eyebrow">
            AI CREATIVE PORTFOLIO
          </div>

          <h1>
            FRANS — AI CREATIVE
            <br />
            &amp; VISUAL DESIGNER
          </h1>

          <p>
            AI Video • AI Image • Social Media Content • Creative Advertising
          </p>

          <div className="portfolio-meta">
            <span>10 SELECTED PROJECTS</span>
            <span>•</span>
            <span>2026</span>
          </div>
        </header>

        {/* HERO BANNER */}
        <section className="hero-banner">
          <img
            src="/about-me.jpg"
            alt="Frans — AI Creative & Visual Designer"
          />
        </section>

 {/* BOTTOM BANNER SAMPEL DESIGN */}
        <section className="bottom-banner">
          <img
            src="/sampledesign.png"
            alt="Frans AI Creative Portfolio"
          />
        </section>

        <h1>
            MY PROJECTS GENERATED BY AI : 
          </h1>


        {/* PROJECT GRID */}
        <section className="works-grid">
          {works.map((work) => {
            const youtubeId = getYouTubeId(work.video);

            return (
              <a
                key={work.title}
                href={work.video}
                target="_blank"
                rel="noopener noreferrer"
                className="work-card"
              >
                <img
                  src={`https://img.youtube.com/vi/${youtubeId}/hqdefault.jpg`}
                  alt={work.title}
                />

                <div className="work-overlay">
                  <div className="play-button">
                    ▶
                  </div>
                </div>

                <div className="work-title">
                  {work.title}
                </div>
              </a>
            );
          })}
        </section>

        {/* VIDEO SHOWCASE 16:9*/}
<section className="showcase-section">
  <div className="showcase-grid">
    {showcaseVideos.map((video) => {
      const youtubeId = getYouTubeId(video.video);

      return (
        <a
          key={video.title}
          href={video.video}
          target="_blank"
          rel="noopener noreferrer"
          className="showcase-card"
        >
          <img
            src={`https://img.youtube.com/vi/${youtubeId}/maxresdefault.jpg`}
            alt={video.title}
          />

          <div className="showcase-overlay">
            <div className="showcase-play">▶</div>
          </div>

          <div className="showcase-title">
            {video.title}
          </div>
        </a>
      );
    })}
  </div>
</section>

        {/* BOTTOM BANNER Certificate */}
        <section className="bottom-banner">
          <img
            src="/certificate.png"
            alt="Frans AI Creative Portfolio"
          />
        </section>
        {/* BOTTOM BANNER TOOLS AI */}
        <section className="bottom-banner">
          <img
            src="/toolsai.png"
            alt="Frans AI Creative Portfolio"
          />
        </section>
{/* BOTTOM BANNER PENUTUP */}
        <section className="bottom-banner">
          <img
            src="/penutup.png"
            alt="Frans AI Creative Portfolio"
          />
        </section>
{/* SOCIAL LINKS */}
<div className="social-links">

  {/* INSTAGRAM */}
  <a
    href="https://www.instagram.com/fr7frans/"
    target="_blank"
    rel="noopener noreferrer"
    aria-label="Instagram"
  >
    <svg viewBox="0 0 24 24" aria-hidden="true">
      <rect
        x="3"
        y="3"
        width="18"
        height="18"
        rx="5"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
      />
      <circle
        cx="12"
        cy="12"
        r="4"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
      />
      <circle
        cx="17.5"
        cy="6.5"
        r="1"
        fill="currentColor"
      />
    </svg>
  </a>

  {/* LINKEDIN */}
  <a
    href="https://www.linkedin.com/in/fr7frans"
    target="_blank"
    rel="noopener noreferrer"
    aria-label="LinkedIn"
  >
    <svg viewBox="0 0 24 24" aria-hidden="true">
      <rect
        x="3"
        y="3"
        width="18"
        height="18"
        rx="2"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
      />
      <circle
        cx="8"
        cy="8"
        r="1.2"
        fill="currentColor"
      />
      <path
        d="M7 11v6M11 17v-3.2c0-1.6.8-2.5 2.1-2.5 1.4 0 1.9 1 1.9 2.5V17M11 11v6"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
      />
    </svg>
  </a>

  {/* YOUTUBE */}
  <a
    href="https://www.youtube.com/@Fr7Frans"
    target="_blank"
    rel="noopener noreferrer"
    aria-label="YouTube"
  >
    <svg viewBox="0 0 24 24" aria-hidden="true">
      <path
        d="M21.2 7.1a2.8 2.8 0 0 0-2-2C17.5 4.6 12 4.6 12 4.6s-5.5 0-7.2.5a2.8 2.8 0 0 0-2 2C2.3 8.8 2.3 12 2.3 12s0 3.2.5 4.9a2.8 2.8 0 0 0 2 2c1.7.5 7.2.5 7.2.5s5.5 0 7.2-.5a2.8 2.8 0 0 0 2-2c.5-1.7.5-4.9.5-4.9s0-3.2-.5-4.9Z"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
      />
      <path
        d="m10 9 5 3-5 3V9Z"
        fill="currentColor"
      />
    </svg>
  </a>

</div>

      </section>

      {/* CONTACT BUTTON */}
      <a
        href="https://wa.me/6285159693977"
        target="_blank"
        rel="noopener noreferrer"
        className="contact-button"
      >
        ◉ &nbsp; Let’s Work Together [My Whatsapp Number]
      </a>
    </main>
  );
}